export const ISLANDS = [
  { code: 'altis', name: 'Алтіс' },
  { code: 'stratis', name: 'Стратіс' },
  { code: 'malden', name: 'Малден' },
  { code: 'tanoa', name: 'Таноа' },
  { code: 'livonia', name: 'Лівонія' },
  { code: 'chernarus', name: 'Чорнорусь' },
  { code: 'chernarus_summer', name: 'Чорнорусь (літо)' },
  { code: 'chernarus_winter', name: 'Чорнорусь (зима)' },
  { code: 'takistan', name: 'Такістан' },
  { code: 'zargabad', name: 'Заргабад' },
  { code: 'utes', name: 'Утес' },
  { code: 'sahrani', name: 'Сахрані' },
  { code: 'southern_sahrani', name: 'Південна Сахрані' },
  { code: 'northern_sahrani', name: 'Північна Сахрані' },
  { code: 'bornholm', name: 'Борнхольм' },
  { code: 'panthera', name: 'Пантера' },
  { code: 'isladuala', name: 'Ісладуала' },
  { code: 'lingor', name: 'Лінгор' },
  { code: 'namalsk', name: 'Намальськ' },
  { code: 'taviana', name: 'Тавіана' },
  { code: 'thirsk', name: 'Тірск' },
  { code: 'thirsk_winter', name: 'Тірск (зима)' },
  { code: 'podagorsk', name: 'Подагорськ' },
  { code: 'fata', name: 'Фата' },
  { code: 'clafghan', name: 'Клафган' },
  { code: 'desert', name: 'Пустеля' },
  { code: 'mountains_acr', name: 'Гори' },
  { code: 'bootcamp_acr', name: 'Буткемп' },
  { code: 'woodland_acr', name: 'Ліс' },
  { code: 'proving_grounds', name: 'Полігон' },
  { code: 'shapur_baf', name: 'Шапур' },
  { code: 'porto', name: 'Порто' },
  { code: 'torabora', name: 'Торабора' },
  { code: 'anizay', name: 'Анізай' },
  { code: 'beketov', name: 'Бекетов' },
  { code: 'celle', name: 'Целле' },
  { code: 'fallujah', name: 'Фаллуджа' },
  { code: 'hellanmaa', name: 'Хелланмаа' },
  { code: 'imrali', name: 'Імралі' },
  { code: 'kunduz', name: 'Кундуз' },
  { code: 'lingor3', name: 'Лінгор 3' },
]